# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University_ID', models.IntegerField()),
                ('University_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
    ]
